apiVersion: agents.x-k8s.io/v1alpha1
kind: Sandbox
metadata:
  name: sandbox-example
spec:
  podTemplate:
    metadata:
      labels:
        sandbox: sandbox-example
    spec:
      containers:
        - name: devcontainer-main
          image: ghcr.io/coder/envbuilder
          env:
            # URL to the repository where the .devcontainer folder we want to load is located
            - name: ENVBUILDER_GIT_URL
              value: "https://github.com/kubernetes-sigs/agent-sandbox.git"
            - name: ENVBUILDER_DEVCONTAINER_DIR
              value: "examples/vscode-sandbox"
            - name: ENVBUILDER_GIT_CLONE_SINGLE_BRANCH
              value: "true"
            - name: ENVBUILDER_INIT_SCRIPT
              value: "/usr/local/bin/code-server-entrypoint"
          volumeMounts:
            - mountPath: /workspaces
              name: workspaces-pvc
  volumeClaimTemplates:
    - metadata:
        name: workspaces-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
