[build]
  base = "site/"
  publish = "public/"

  # A placeholder command that creates the publish directory and a single index.html file.
  # This ensures the build succeeds without needing a full site generator like Hugo yet.
  command = "mkdir -p public && echo 'Placeholder Page' > public/index.html"