apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: prevent-sandbox-sa-binding
  annotations:
    policies.kyverno.io/title: Disallow RoleBindings to Sandbox SAs
    policies.kyverno.io/description: >-
      This policy prevents creating or updating RoleBindings
      and ClusterRoleBindings that grant new permissions to any
      ServiceAccount actively referenced by an Sandbox resource.
spec:
  validationFailureAction: Enforce
  rules:
  - name: block-sandbox-sa-bindings
    match:
      any:
      - resources:
          kinds:
          - RoleBinding
          - ClusterRoleBinding
    validate:
      message: "Binding to a ServiceAccount that is actively in use by an Sandbox is forbidden."
      foreach:
      - list: "request.object.subjects"
        preconditions:
          all:
          - key: "{{element.kind}}"
            operator: Equals
            value: "ServiceAccount"
        context:
        - name: matchingSandboxes
          apiCall:
            urlPath: "/apis/karo.io/v1/namespaces/{{element.namespace}}/sandboxes"
            jmesPath: "items[?spec.serviceAccountRef.name == '{{element.name}}'] | length(@)"
        pattern:
          matchingSandboxes: 0