# This rule is not used by the project agent-sandbox itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over agents.x-k8s.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: agent-sandbox
    app.kubernetes.io/managed-by: kustomize
  name: sandbox-admin-role
rules:
- apiGroups:
  - agents.x-k8s.io
  resources:
  - sandboxes
  verbs:
  - '*'
- apiGroups:
  - agents.x-k8s.io
  resources:
  - sandboxes/status
  verbs:
  - get
